### ISSUE TITLE
Security System Target State sending invalid value

### ISSUE THREAD

**Issue by chrisdaher** [konnected-io/homebridge-konnected#4]
Hi,

I'm trying to connect my Konnected security panel to my homebridge, and it's throwing this warrning/error below.

The result is that I have a constantly spinning "Disarming" garage accessory in my apple home.

Homebridge version: v1.4.1
Homebridge-konnected version: v1.2.1

Every time I open the home app I see this error get printed in homebridge. So there must be some call there that's causing it to fail

`[6/22/2022,` 2:39:01 PM] [homebridge-konnected] This plugin generated a warning from the characteristic 'Security System Target State': characteristic value 0 is not contained in valid values array. See https://homebridge.io/w/JtMGR for more info.

[6/22/2022, 2:39:01 PM] [homebridge-konnected] Error: 
    at SecuritySystemTargetState.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at SecuritySystemTargetState.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:2054:14)
    at SecuritySystemTargetState.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:1582:21)
    at step (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:125:57)
    at /var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:114:16)
    at SecuritySystemTargetState.Characteristic.handleGetRequest (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/dist/lib/Characteristic.js:689:38)
    at SecuritySystemTargetState.<anonymous> (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/src/lib/Characteristic.ts:2207:22)
    at step (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:144:27)
    at Object.next (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:125:57)
    at /var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/var/lib/homebridge/node_modules/.pnpm/tslib@2.4.0/node_modules/tslib/tslib.js:114:16)
    at SecuritySystemTargetState.Characteristic.toHAP (/var/lib/homebridge/node_modules/.pnpm/hap-nodejs@0.10.2/node_modules/hap-nodejs/dist/lib/Characteristic.js:1328:38)`

**Comment by mkormendy** [comment]
Can you clarify with a screenshot of what you're seeing in the Home.app by what you mean with "Disarming garage accessory"?

**Comment by mkormendy** [comment]
I think you meant disarming **alarm** accessory.

In that case, this error in the log is expected and just a warning (not a fatal error). What you need to do is set up some sensor zones and define what mode they trigger the alarm in. Then reboot, and change the state of the alarm system mode to initiate it. The warning will go away after.

I realize that this is not the best experience and I will endeavor to optimize it in a future version.

**Comment by chrisdaher** [comment]
Hi Mike,

Thank you for your prompt response!

Here is the config I have in homebridge, and a few screenshots of it being
stuck in "Disarming" mode. I only see the panel in the home app, I don't
see any of the zones/accessories.

About your comment "Then reboot, and change the state of the alarm system
mode to initiate it", you're saying I should reboot the konnected panel or
homebridge? And how do I change the state of the alarm system mode?

{
    "name": "Konnected",
    "advanced": {
        "exitDelaySettings": {
            "audibleBeeperModes": [
                "false",
                "false",
                "1"
            ]
        }
    },
    "panels": [
        {
            "name": "Panel",
            "ipAddress": <IP OF ALARM PANEL>,
            "port": 13678,
            "blink": true,
            "zones": [
                {
                    "enabled": true,
                    "zoneNumber": "1",
                    "zoneType": "contact",
                    "zoneLocation": "Entrance"
                },
                {
                    "enabled": true,
                    "zoneNumber": "2",
                    "zoneType": "motion",
                    "zoneLocation": "Basement"
                },
                {
                    "enabled": true,
                    "zoneNumber": "3",
                    "zoneType": "contact",
                    "zoneLocation": "Patio"
                },
                {
                    "enabled": true,
                    "zoneNumber": "4",
                    "zoneType": "motion",
                    "zoneLocation": "Living Room"
                }
            ]
        },
        {
            "name": "Konnected V1-V2",
            "uuid": <UUID>,
            "ipAddress": <IP OF ALARM PANEL>,
            "port": 13678
        }
    ],
    "platform": "konnected"
}

**Comment by mkormendy** [comment]
Looking at your config, there are a couple problems:
- you seem to have two alarm panels listed. If you only have one, that should be corrected
- the audible beeper modes should have no "false" values

> About your comment "Then reboot, and change the state of the alarm system
> mode to initiate it", you're saying I should reboot the konnected panel or
> homebridge? And how do I change the state of the alarm system mode?

I meant to say reboot Homebridge.

Have you set any of the Binary Sensor Settings with the Triggerable Modes?
In this case if you want just Away or Off, you have Away (value "1" per the documentation) for each of the Contact or Motion sensor assigned zones.

Try the following config block for Konnected (fixed number of panels, audible beeper modes, and added triggerable modes for each sensor):

```
{
    "name": "Konnected",
    "advanced": {
        "exitDelaySettings": {
            "audibleBeeperModes": [
                "1"
            ]
        }
    },
    "panels": [
        {
            "name": "Konnected V1-V2",
            "uuid": <UUID>,
            "ipAddress": <IP OF ALARM PANEL>,
            "port": 13678,
            "blink": true,
            "zones": [
                {
                    "enabled": true,
                    "zoneNumber": "1",
                    "zoneType": "contact",
                    "zoneLocation": "Entrance",
                    "binarySensorSettings": {
                        "triggerableModes": [
                            "1"
                        ]
                    }
                },
                {
                    "enabled": true,
                    "zoneNumber": "2",
                    "zoneType": "motion",
                    "zoneLocation": "Basement",
                    "binarySensorSettings": {
                        "triggerableModes": [
                            "1"
                        ]
                    }
                },
                {
                    "enabled": true,
                    "zoneNumber": "3",
                    "zoneType": "contact",
                    "zoneLocation": "Patio",
                    "binarySensorSettings": {
                        "triggerableModes": [
                            "1"
                        ]
                    }
                },
                {
                    "enabled": true,
                    "zoneNumber": "4",
                    "zoneType": "motion",
                    "zoneLocation": "Living Room",
                    "binarySensorSettings": {
                        "triggerableModes": [
                            "1"
                        ]
                    }
                }
            ]
        }
    ],
    "platform": "konnected"
}
```

**Comment by chrisdaher** [comment]
Hi Mike,

I fixed the config based on what you gave me, and now I'm able to
ARM/DISARM. However, I still only see the alarm panel in Apple Home app, I
don't see any of the zones/sensors. Also when activating a sensor, it
doesn't show any change on the home app.

Is there any way to have the zones show up on the home app so I can also
use them as regular sensors (i.e. turn on a light when a sensor is
activated etc...)?

Chris

**Comment by roycepope** [comment]
The sensors should show up like regular sensors. They will all drop in your default room in the home app. I had to manually put all my sensors in the appropriate room after adding them in homebridge.

**Comment by mkormendy** [comment]
> Can you clarify with a screenshot of what you're seeing in the Home.app by what you mean with "Disarming garage accessory"?

I'm still waiting for the screenshot, regardless of the "garage" mixup.

**Comment by chrisdaher** [comment]
Hi Mike,

My alarm panel now works fine, i can arm and disarm, but the new issue i’m
facing now is that I cannot see my sensors/zones. I did check all the rooms
and didn’t find them.

Chris

**Comment by mkormendy** [comment]
I see you already said that.

Can you provide a screen capture of the Home.app?

**Comment by helo-head** [comment]
> Try the following config block for Konnected (fixed number of panels, audible beeper modes, and added triggerable modes for each sensor):
> 
> ```
> {
>     "name": "Konnected",
>     "advanced": {
>         "exitDelaySettings": {
>             "audibleBeeperModes": [
>                 "1"
>             ]
>         }
>     },


I had the same or similar issue (invalid state) as initially reported on first configuration. I fixed it by changing the "audibleBeeperModes" from false,false,1 to just 1. 

Not sure why this was causing the issue but rule 25 states never argue with success. Works fine now. 

Here is part of the original error message.

[11/10/2022, 20:09:45] [homebridge-konnected] This plugin generated a warning from the characteristic 'Security System Target State': characteristic value 0 is not contained in valid values array. See https://homebridge.io/w/JtMGR for more info.
