### ISSUE TITLE
SSDP error - No sockets available, cannot start.

### ISSUE THREAD

**Issue by robotastic** [konnected-io/homebridge-konnected#5]
Any thoughts on what might be causing this error? Rebooting seems to fix it. I am running Homebridge on an Ubuntu 22.04 box. It is running Homebridge v1.5.0 and the latest version of the plugin.

````
Unhandled rejection Error: No sockets available, cannot start.
    at SsdpClient.SSDP._createSockets (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:186:11)
    at SsdpClient.SSDP._start (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/index.js:229:10)
    at /var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/client.js:60:10
    at Promise._execute (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/bluebird/js/release/promise.js:103:10)
    at SsdpClient.start (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/client.js:54:10)
    at SsdpClient.search (/var/lib/homebridge/node_modules/homebridge-konnected/node_modules/node-ssdp/lib/client.js:82:17)
    at KonnectedHomebridgePlatform.discoverPanels (/var/lib/homebridge/node_modules/homebridge-konnected/src/platform.ts:328:16)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-konnected/src/platform.ts:395:14)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
````

**Comment by mkormendy** [comment]
This plugin is no longer managed by me at this location, I will be working on it and managing issues on my own GitHub repo externally under @mkormendy.
